modLoader="javafml"
license="MIT License https://github.com/McJtyMods/FXControl/blob/1.16/LICENCE"
loaderVersion="[43,)"
issueTrackerURL="http://github.com/McJtyMods/FxControl/issues"
displayURL="http://github.com/McJtyMods/FxControl/"
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="McJty"

[[mods]]
modId="fxcontrol"
version="${file.jarVersion}"
displayName="FxControl"
#updateJSONURL="http://myurl.me/" #optional
description='''
Be in control of effects
'''
[[dependencies.fxcontrol]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.30,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.incontrol]]
    modId="lostcities"
    mandatory=false
    versionRange="[1.19-6.0.6,)"
    ordering="NONE"
    side="BOTH"
