modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="http://github.com/McJtyMods/FxControl/issues"
displayURL="http://github.com/McJtyMods/FxControl/"
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="McJty"

[[mods]]
modId="fxcontrol"
version="${file.jarVersion}"
displayName="FxControl"
#updateJSONURL="http://myurl.me/" #optional
description='''
Be in control of effects
'''
[[dependencies.fxcontrol]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
